import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import { Navigation } from "./components/Navigation";
import ClientWrapper from "./providers";

import { cookies } from "next/headers";
import { logout } from "@/services/userServices";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;

  const isLogedIn = !!token;
  console.log("IS LOGED IN:", isLogedIn);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClientWrapper>
          <Navigation isLogedIn={isLogedIn} />
          {children}
          <Footer />
        </ClientWrapper>
      </body>
    </html>
  );
}
